# Jekyll theme
theme: jekyll-theme-midnight
# Set up
title: Camilo Marchesini
email: camilo.marchesini@gmail.com
description: Camilo Marchesini's personal website

url: https://camilomrch.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Repository
repository: camilomrch/camilomrch.github.io

# Contact
author:
  name: Camilo Marchesini

github_username: camilomrch

# Build settings
# others
markdown: kramdown
github: [metadata]
input: GFM
plugins:
  - jekyll-feed
  - jekyll-sitemap
