
# Set up
title: Welcome!
email: camilo.marchesini@gmail.com
description: Camilo Marchesini's website
baseurl: "" # the subpath of your site, e.g. /blog

# Repository
repository: camilomrch/camilomrch.github.io

# Contact
author:
  name: Camilo Marchesini
  url: "https://camilomrch.github.io"

github_username: camilomrch

# Build settings
# others
markdown: kramdown
include: ['_pages']
github: [metadata]
theme: jekyll-theme-midnight
input: GFM
plugins:
  - jekyll-feed
  - jekyll-sitemap
